### ISSUE TITLE
Please publish this extension on Chrome WebStore

### ISSUE THREAD

**Issue by kaurov** [StegSchreck/is24-price-per-area#3]
Please publish this extension on https://chrome.google.com/webstore/category/extensions?hl=de so users without developers skills can install it.

**Comment by StegSchreck** [comment]
Chrome Webstore docs: https://developer.chrome.com/docs/webstore/publish/
Github Action for automated publishing: https://github.com/marketplace/actions/chrome-extension-upload-action
